### ISSUE TITLE
The statement "c.transform = lambda x: self(x)[:, *item]" is causing an issue.

### ISSUE THREAD

**Issue by cszmzh** [franciscogaluppo/tiny-dc3#1]
I am using Python 3.8, and I'm encountering an error during runtime:
![iShot_2023-12-26_17 25 07](https://github.com/franciscogaluppo/tiny-dc3/assets/45927088/ceb4ebdf-798f-4afd-bb44-0f1b19cf978f)

**Comment by franciscogaluppo** [comment]
Tested using 3.8 and it indeed raised a SyntaxError, but it didn't on 3.11.

This is likely due to the unpacking operator * being used inside the subscript operator []. This syntax was not legal in Python 3.8 and earlier versions. The unpacking syntax wasn't permitted inside of subscripts (indexing/slicing operations) until Python 3.10 with the introduction of PEP 637.

Are you able to use newer versions of Python?
